### ISSUE TITLE
An Aspirational Wishlist 

### ISSUE THREAD

**Issue by mike-thompson-day8** [day8/re-frame-10x#118]
## The Bullet List

A central wish list  (individual items will ultimately become a separate issue): 
  - [x] what changes/deltas to `app-db` occurred.  How about to each of the nominated paths. Can I switch backwards and forwards to see the value at a path and the delta?
  - [x] which subscriptions ran  (show deltas too). Which subscriptions did not run. 
  - [x] in the trace show me markers for begin-annimation-frame and end-animation-frame
  - [x] a high level summary: how long did it take, how many subscription handlers ran, how many animation frames were used, etc. 
  - [x] the event  (may be too big to render?)
  - [x] how many coeffects handlers ran?  Which ones?
  - [x] what event handler ran? Data inputs/outputs?
  - [x] what effects? 
  - [x] what effects handlers ran? 
  - [x] which views re-rendered?  
  - [x] how to better process and display "intra" epoch trace - mouse-over rendering etc. 
  - [x] add a "RePlay" button to the tabs layer  #155. See also [these docs](https://github.com/Day8/re-frame-10x/blob/master/docs/HyperlinkedInformation/ReplayButton.md)
  - [x] Provide a way too make trace data available in the figwheel REPL for further experimentation. Something like [scope-capture](https://github.com/vvvvalvalval/scope-capture). Click button to copy an expression which gives you access to the data that you can take to the REPL.
  - [ ] What hiccup did views return? Deltas to last time? Careful of functions. 
  - [ ] User should be told if any views ran unnecessarily? Same hiccup as last time? 
  - [ ] better filtering in some tabs.  Eg. events and subscriptions. 
  - [ ] User should be told if bad subscription "patterns" are detected.  #148
  - [ ] User should see if an exception occured during the epoch?  Big red bar to tell me to look in `js/console`?
  - [ ] User should be able to easily navigate to handler source code (events, subscriptions, effects, interceptors). No idea how to do this other than with macros - booo - perhaps we can just write stacktraces into js/console so they can be source mapped. Click a button in the `re-frame-10x`  to see stacktraces put into  the dashboard?
  - [ ] As above, user should easily find out from where an event was `dispatch`-ed. Source code coordinates. 
  - [ ] the programmer should be able to produce trace themselves  and have it appear in `re-frame-trace`.  See #149.
  - [ ] show a graph of subs. How data flows from `app-db` up the tree to the views. Use [cytoscape.js](http://www.cytoscape.org/)?
  - [ ] show a graph of views.  Will be big. Probably too big. Too much noise because of the VBoxes and HBoexs of this world.  But if we exclude HBox etc. there will be discontinuities. 
  - [ ] better interaction with the chrome profile API.  See #28 
  - [x] ~buttons to save `app-db` to local store and then restore. Useful if you have to restart the application and you want to immediately get back into the right state.  #112~
 - [x] <s>make timings more accurate by repeating an event 50 times and averaging. See #113 </s>

## UI Mocks

We use figma, which is not very good for OSS, sorry, but its is the tool we know. 

Here are the mocks: https://www.figma.com/file/EXTcBzsMoORAOb4dd8GFsgko/re-frame-trace-mock
 
Todo:

   - [x] mock a better events panel 
   - [ ] mock the "views" panel 
   - [ ] mock a better way of viewing the  execution chain for "interceptors".

**Comment by mike-thompson-day8** [comment]
Some very preliminary mocking of final concept taking place via figma. 
https://www.figma.com/file/EXTcBzsMoORAOb4dd8GFsgko/re-frame-trace-mock

**Comment by mike-thompson-day8** [comment]
So a new version has just been released.  We're continuing to move towards the mocks in:
https://www.figma.com/file/EXTcBzsMoORAOb4dd8GFsgko/re-frame-trace-mock
